version: "3.8"

services:
  backend:
    build: 
      context: ./be
    ports:
      - "8000:8000"
    volumes:
      - ./be:/app
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/ats
    depends_on:
      - elasticsearch
      - redis
      - postgres

  frontend:
    build:
      context: ./fe
    ports:
      - "5173:5173"
    volumes:
      - ./fe:/app
    environment:
      - VITE_API_URL=http://localhost:8000

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ats
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
